// src/views/page1.jsx
export default {
    data() {
        return {
            tableData: [{
                date: '2016-05-02',
                name: '王小虎',
                address: '上海市普陀区金沙江路 1518 弄'
            }, {
                    date: '2016-05-04',
                    name: '王小虎',
                    address: '上海市普陀区金沙江路 1517 弄'
                }, {
                    date: '2016-05-01',
                    name: '王小虎',
                    address: '上海市普陀区金沙江路 1519 弄'
                }, {
                    date: '2016-05-03',
                    name: '王小虎',
                    address: '上海市普陀区金沙江路 1516 弄'
                }]
        }
    },
    name: "page1",
    render(h) {
        return (
            <el-table data={this.tableData} style="width: 100%">
                <el-table-column
                    property="date"
                    label="日期"
                    width="180">
                </el-table-column>
                <el-table-column
                    property="name"
                    label="姓名"
                    width="180">
                </el-table-column>
                <el-table-column
                    property="address"
                    label="地址">
                </el-table-column>
            </el-table>
        )
    }
}

// src/views/page1.vue
<template>
    <div class="el-row">
        <div class="el-col-24">
            <el-table :data="tableData" style="width: 100%">
                <el-table-column
                        property="date"
                        label="日期"
                        width="180">
                </el-table-column>
                <el-table-column
                        property="name"
                        label="姓名"
                        width="180">
                </el-table-column>
                <el-table-column
                        property="address"
                        label="地址">
                </el-table-column>
            </el-table>
          </div>
       </div>
</template>
<script>
    export default {
        name: "page1",
        data() {
            return {
                tableData: [{
                    date: '2016-05-02',
                    name: '王小虎',
                    address: '上海市普陀区金沙江路 1518 弄'
                }, {
                    date: '2016-05-04',
                    name: '王小虎',
                    address: '上海市普陀区金沙江路 1517 弄'
                }, {
                    date: '2016-05-01',
                    name: '王小虎',
                    address: '上海市普陀区金沙江路 1519 弄'
                }, {
                    date: '2016-05-03',
                    name: '王小虎',
                    address: '上海市普陀区金沙江路 1516 弄'
                }]
            }
        }
    }

</script>
<style>

</style>
